using QuestPDF.Fluent;
using QuestPDF.Infrastructure;
using WebWork.Models;

namespace WebWork.Services;

public interface IDocumentService
{
    byte[] GenerateProjectPdf(Project project);
}

public class DocumentService : IDocumentService
{
    public byte[] GenerateProjectPdf(Project project)
    {
        // Лицензия задаётся на старте приложения (QuestPDF.Settings.License).
        return Document.Create(container =>
        {

            container.Page(page =>
            {
                page.Margin(20);
                page.Header().Text($"Коммерческое предложение: {project.Title}").FontSize(18).Bold();

                page.Content().Column(col =>
                {
                    col.Item().Text($"Срок: {project.StartDate:dd.MM.yyyy} - {project.EndDate:dd.MM.yyyy}");
                    col.Item().Text($"Итого: {project.TotalCostWithMargin:0.00}");

                    foreach (var r in project.Resources)
                        col.Item().Text($"{r.ResourceName} | {r.ServiceName} | {r.UnitsCount} | {r.FinalCost:0.00}");
                });

                page.Footer().AlignRight().Text("Generated by system");
            });
        }).GeneratePdf();
    }
}