<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>

    <!-- Восстановить стандартные glob’ы компиляции, чтобы исключить двойную сборку файлов -->
    <EnableDefaultItems>true</EnableDefaultItems>
    <EnableDefaultCompileItems>true</EnableDefaultCompileItems>
  </PropertyGroup>



  <ItemGroup>
    <PackageReference Include="EPPlus" Version="8.6.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.3" />

    <!-- EF Core runtime + provider (чтобы скомпилировались DbContext/DbSet/UseSqlServer) -->
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.0" />

    <!-- инструменты миграций -->
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>

    <PackageReference Include="QuestPDF" Version="2026.5.0" />

    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>


  <ItemGroup>
    <!-- Временно исключаем проблемный файл, чтобы пройти сборку и продолжить сдачу проекта -->
    <Compile Remove="Services\ProjectCalculationService.cs" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.0" />
  </ItemGroup>

</Project>
